### ISSUE TITLE
Erros ao preencher cartão

### ISSUE THREAD

**Issue by carcleo** [mercadopago/card-payment-sample#4]
Ao preencher o numero do cartão, muitos de erros de js nas chamadas a API

**Comment by rdmoedas** [comment]
Tive esses erros quando colei os dados do cartão com espaço, digitando apenas os números do cartão a API chamou sem problemas.
Talvez bloquear entrada de " " ajuda evitar esses erros.

**Comment by lucasctd** [comment]
@rdmoedas tu conseguiu fazer esse exemplo funcionar? Aqui sempre da erro de SSL.

`Uncaught Exception: SSL certificate problem: unable to get local issuer certificate in C:\Wnmp\html\server\php\vendor\mercadopago\dx-php\src\MercadoPago\RestClient.php:196`

**Comment by carcleo** [comment]
Até agora nada!

**Comment by rdmoedas** [comment]
> @rdmoedas tu conseguiu fazer esse exemplo funcionar? Aqui sempre da erro de SSL.
> 
> `Uncaught Exception: SSL certificate problem: unable to get local issuer certificate in C:\Wnmp\html\server\php\vendor\mercadopago\dx-php\src\MercadoPago\RestClient.php:196`

@lucasctd Opa blz? Experimenta usar algum serviço de tunnel tipo o Ngrok, com ele da para deixar o servidor local em um endereço https ou http, eu utilizei ele em alguns testes
[Se quiser tem esse guia](https://medium.com/desenvolvendo-com-paixao/ngrok-do-localhost-para-o-mundo-5445ad08419)

**Comment by lucasctd** [comment]
@rdmoedas Eu coloquei num servidor online meu mesmo, só que o exemplo deles sempre retorna nulo como resposta do provedor de pagamento.

**Comment by nicolassalvanes** [comment]
Olá @carcleo @lucasctd,

Pedimos desculpas pelo atraso.

Informamos que recentemente carregamos uma nova versão de nossos exemplos, incluindo um repositório separado para o exemplo [PHP](https://github.com/mercadopago/card-payment-sample-php).
Você pode testá-lo e verificar se funciona corretamente, caso algum erro persista, escreva-nos novamente criando um Issue no repositório correspondente.

Obrigado por nos contatar

a equipe do Mercado Pago.
