### ISSUE TITLE
No support for any web development framework

### ISSUE THREAD

**Issue by JamesUNT** [mercadopago/card-payment-sample#7]
I'm struggling to integrate the lib with my vue/quasar application, but it seems the MercadoPago's CDN doesn't work with those virtual DOM based frameworks.

Found this guy having the same issue and yet no response:
https://stackoverflow.com/questions/67894623/error-mercadopago-js-could-not-find-html-element-for-provided-id-mphiddeninp 

and please, pack this lib. and publish it on NPM.

**Comment by biaguerreiromeli** [comment]
Hola, @JamesUNT 👋 

Le pedimos disculpas por la demora de respuesta y por el inconveniente en su fluxo de trabajo.

Aun siendo abierto, este espacio no pretende servir como herramienta de soporte a la problemática inherente a la plataforma y sus integraciones. Solo está destinado a almacenar código y documentaciones públicos.

**Tenemos un canal oficial de soporte súper preparado para solucionar rápidamente tu caso.**
Por eso, si el error persiste, recopile toda la información y accede aquí para compartir conosco el problema: https://www.mercadopago.com/developers/es/support

¡Muchas gracias por su contacto!
